t3

diff --git a/.github/workflows/pocCICD.yml b/.github/workflows/pocCICD.yml
--- a/.github/workflows/pocCICD.yml
+++ b/.github/workflows/pocCICD.yml
@@ -46,42 +46,50 @@ jobs:
       - name: Validate script names in IL files
         run: |
           echo "IL LIST: ${var_il_list}"
-          for il in ${var_il_list}
-          do
-            export err=0
-            for fname in ${il}
+          if [ "${var_il_list}" != "" ]; then
+            for il in ${var_il_list}
             do
-              var_file=`echo ${fname} | awk -F: '{print $2}'`
-              if [ `ls ${var_file} | wc -l` -eq 0 ]; then
-               echo ${il}: ${var_file} does not exists
-               export err=`expr ${err} + 1`
-              fi
-            done
-           done
-           echo "err: ${err}"
-           if [ ${err} -gt 0 ]; then
-             echo "Errors while validating IL files"
-             exit 1
-           fi
-          echo "IL validation completed successfully..."
+              export err=0
+              for fname in ${il}
+              do
+                var_file=`echo ${fname} | awk -F: '{print $2}'`
+                if [ `ls ${var_file} | wc -l` -eq 0 ]; then
+                 echo ${il}: ${var_file} does not exists
+                 export err=`expr ${err} + 1`
+                fi
+              done
+             done
+             echo "err: ${err}"
+             if [ "${err}" = "0" ]; then
+               echo "IL validation completed successfully..."
+             else
+               echo "Errors while validating IL files"
+               exit 1
+             fi
+          else
+            echo "Skipping validation..."
+          fi
           
       - name: Create build for each IL
         run: |
           export builds=
-          for j in ${var_il_list}
-          do
-            tar_name=`echo ${j} | awk -F. '{print $1}'`.tar
-            for f1 in ${il}
+          if [ "${var_il_list}" != "" ]; then
+            for j in ${var_il_list}
             do
-              var_file=`echo ${fname} | awk -F: '{print $2}'`
-              export var_files=`echo ${var_files} ${var_file}`
-            done
-            tar -cf ${tar_name} ${var_files}
-            if [ $? -eq 0 ]; then
-              export builds=`echo ${builds} ${tar_name}`
-            else
-              echo "Error while creating ${tar_name}"
-              exit 1
-            fi
-           echo "Builds created successfully: ${builds}"
-        
+              tar_name=`echo ${j} | awk -F. '{print $1}'`.tar
+              for f1 in ${il}
+              do
+                var_file=`echo ${fname} | awk -F: '{print $2}'`
+                export var_files=`echo ${var_files} ${var_file}`
+              done
+              tar -cf ${tar_name} ${var_files}
+              if [ $? -eq 0 ]; then
+                export builds=`echo ${builds} ${tar_name}`
+              else
+                echo "Error while creating ${tar_name}"
+                exit 1
+              fi
+             echo "Builds created successfully: ${builds}"
+           else
+             echo "Skipping build creation..."
+           fi
